---
apiVersion: v1
kind: Service
metadata:
  name: homeassistantservice
  labels:
    app: homeassistant
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8123
    nodePort: 30123
  selector:
    app: homeassistant
