---
apiVersion: v1
kind: Service
metadata:
  name: homeassistantservice
  labels:
    app: homeassistant
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8123
    nodePort: 30123
  selector:
    app: homeassistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeautomationdeployment
  labels:
    app: homeassistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:0.84.5
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
        - name: config
          hostPath:
            path: /home/packet
